version: '3.7'
services:
  frontend:
    ports:
      - "3000:3000"
    build:
      context: frontend
    environment:
      - LANDLORD_ADDRESS
      - RPC_URL
    container_name: frontend

  backend:
    ports:
      - "8000:8000"
    build:
      context: backend
    environment:
      - LANDLORD_ADDRESS
      - RPC_URL
    container_name: backend

  solution-web:
    image: nginx:1.17
    volumes:
      - ./nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
