version: '3.7'
services:
  frontend:
    ports:
      - "3000:3000"
    build:
      context: frontend
    environment:
      - LANDLORD_ADDRESS
      - RPC_URL
    container_name: solution-frontend

  backend:
    ports:
      - "8000:8000"
    build:
      context: .
      dockerfile: backend/Dockerfile
    environment:
      - LANDLORD_ADDRESS
      - RPC_URL
    container_name: solution-backend

  solution-web:
    build:
      context: reverseproxy
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    container_name: solution-web
